apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher-service
    version: dispatcher
    service: dispatcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher-service
      version: dispatcher
      service: dispatcher-service
  template:
    metadata:
      labels:
        app: dispatcher-service
        version: dispatcher
        service: dispatcher-service
    spec:
      containers:
        - name: dispatcher-service
          image: ghcr.io/gmdcjdakdcjd/dispatcher-service:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9003
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_RABBITMQ_HOST
              value: polar-rabbitmq

---

apiVersion: v1
kind: Service
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher-service
    version: dispatcher
    service: dispatcher-service
spec:
  type: ClusterIP
  selector:
    app: dispatcher-service
    version: dispatcher
  ports:
  - protocol: TCP
    port: 80
    name: tcp
    targetPort: 9003
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
    version: config
    service: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
      version: config
      service: config-service
  template:
    metadata:
      labels:
        app: config-service
        version: config
        service: config-service
    spec:
      containers:
        - name: config-service
          image: ghcr.io/gmdcjdakdcjd/config-service:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 80
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"

---
apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-service
    version: config
    service: config
spec:
  type: ClusterIP
  selector:
    app: config-service
    version: config
    service: config-service
  ports:
  - protocol: TCP
    port: 8888 
    name: tcp 
    targetPort: 8888 
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
    version: order
    service: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
      version: order
      service: order-service
  template:
    metadata:
      labels:
        app: order-service
        version: order
        service: order-service
    spec:
      containers:
        - name: order-service
          image: ghcr.io/gmdcjdakdcjd/order-service:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9000
          env:
            - name: POLAR_CATALOG_SERVICE_URI
              value: http://catalog-service
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service
            - name: SPRING_RABBITMQ_HOST
              value: polar-rabbitmq
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://polar-postgres/polardb_order
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://polar-postgres/polardb_order
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: http://polar-keycloak/realms/PolarBookshop

---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  labels:
    app: order-service
    service: order-service
    version: order
spec:
  type: ClusterIP
  selector:
    app: order-service
    service: order-service
    version: order
  ports:
  - protocol: TCP
    port: 80
    name: tcp
    targetPort: 9002
